[package]
name = "lib_cpi"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "1.0.140", features = ["preserve_order"] }
serde = { version = "1.0.140", features = ["derive"] }
lib_cpi_macros = { path = "../lib_cpi_macros" }