[package]
name = "lib_cpi_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = { version = "1.0.40", features = ["proc-macro"] }
syn = { version = "2.0.101", features = ["full"] }

[lib]
proc-macro = true